[#88] Elastic Search 를 이용한 검색 기능을 구현한다.
milzipmoza-developers/tecobrary-server-api-v2 pull request #145
Opened 2020-01-01 12:57 UTC by skygl

2020-01-01 15:00 UTC, ghost requested changes
👍 👍  결국 해내셨군요 ㅎㅋㅋ
간단한 코멘드만 남겼어요~

2020-01-01 15:00 UTC, ghost commented on src/main/java/com/woowacourse/tecobrary/librarybook/domain/ESLibraryBookRepository.java
> +    private SearchRequest createSearchRequest(final String keyword) {
searchByKeyword 메서드 밑에 위치해야 할 것 같아요~

2020-01-01 15:00 UTC, ghost commented on src/main/java/com/woowacourse/tecobrary/librarybook/domain/ESLibraryBookRepository.java
> +    private static final SearchHitsMapper<LibraryBookResponseDto> LIBRARY_BOOKS_RESPONSE_DTO_MAPPER = searchHit -> {
Mapper는 따로 클래스로 빼는게 어떨까요~??

2020-01-01 15:00 UTC, ghost commented on src/main/java/com/woowacourse/tecobrary/librarybook/ui/LibraryBookSearchController.java
> +                                             @RequestParam final int page, @RequestParam final int size) {
size 도 한줄 밑으로 내리면 어떨까요~?~?

2020-01-01 15:00 UTC, ghost commented on src/test/java/com/woowacourse/tecobrary/librarybook/application/ESLibraryBookServiceTest.java
> +    @DisplayName("키워드에 해당하는 도서를 조회한다.")
`키워드를 포함하는 정보를 가진 도서를 조회한다.` 어떤가요??

흠.. 좋은 이름이 생각이 안나네요.
이건 잘 모르겠네요..ㅋㅋㅋ

컨트롤러 테스트는 없나요 ??

2020-01-02 13:37 UTC, TheDevLuffy commented on src/test/java/com/woowacourse/tecobrary/librarybook/application/ESLibraryBookServiceTest.java
> +    @DisplayName("키워드에 해당하는 도서를 조회한다.")
``키워드를 포함하는 도서를 조회한다.`` 는 어떨까요 ?

2020-01-02 13:41 UTC, workromancer requested changes
이지~ 고생하셨습니다 !
Url Mapping 은 기존에 있던
```java
@GetMapping("/books/search")
    public ResponseEntity readLibraryBooksByTitle(@RequestParam final int page, @RequestParam final int number, @RequestParam final String title) {
        return ResponseEntity.ok(libraryBookCRUDService.findAllByTitleContaining(title, page, number));
    }
```
를 현재 기능이 대체하니까 위의 기능을 제거하고 교체하면 될 것 같아요.

혹시 wiki 에 elk 실행 방법도 정리해서 올려주실 수 있나요?

2020-01-02 13:41 UTC, TheDevLuffy commented on src/main/java/com/woowacourse/tecobrary/librarybook/domain/ESLibraryBookRepository.java
> +                    .collect(Collectors.toList());
메서드로 분리하는 것은 어떨까요?

2020-01-02 13:41 UTC, TheDevLuffy commented on src/main/java/com/woowacourse/tecobrary/librarybook/domain/ESLibraryBookRepository.java
> +        return searchRequest;
메서드로 분리하는 것은 어떨까요?

2020-01-03 00:22 UTC, skygl commented on src/main/java/com/woowacourse/tecobrary/librarybook/domain/ESLibraryBookRepository.java
> +    private SearchRequest createSearchRequest(final String keyword) {
자동 포맷팅 하다가 바뀐 것 같네요 ㅎ

2020-01-03 00:32 UTC, skygl commented on src/test/java/com/woowacourse/tecobrary/librarybook/application/ESLibraryBookServiceTest.java
> +    @DisplayName("키워드에 해당하는 도서를 조회한다.")
`키워드를 포함하는 도서를 조회한다.` 로 바꿀게요.

2020-01-03 00:41 UTC, skygl commented
LibraryBook 도메인의 필드들의 String형들(`title, author, publisher 등`)을 LibraryBook 도메인에 상수로 넣는건 어떨까요??

2020-01-05 04:30 UTC, ghost approved these changes
title 등의 필드를 상수로 둔다는게 어떻게 되는 것인가요??
이해가 잘 안되네요..

2020-01-06 01:23 UTC, workromancer requested changes
마지막 리뷰가 될 것 같아요 !
그런데 마지막으로 [코멘트 남기신 부분](https://github.com/milzipmoza-developers/tecobrary-server-api-v2/pull/145#issuecomment-570417529)은 이해가 잘 되지 않아요.
부연 설명 부탁드릴께요 ㅎㅎ

2020-01-06 01:23 UTC, TheDevLuffy commented on src/main/java/com/woowacourse/tecobrary/librarybook/ui/LibraryBookSearchController.java
> +    @GetMapping("/book/search")
``/books/search`` 로 변경하고 LibraryBookController 의 기존에 이 역할을 담당하고 있는 메서드인 ``readLibraryBooksByTitle`` 을 제거하면 좋을 것 같아요.

2020-01-07 02:51 UTC, skygl commented on src/main/java/com/woowacourse/tecobrary/librarybook/ui/LibraryBookSearchController.java
> +    @GetMapping("/book/search")
기존 메서드를 `/books/title/search` 로 바꾸는건 어떨까요?
어드민 페이지에서의 검색같이 무결성이 중요한 경우에는 데이터베이스에서 직접 조회해야한다고 생각해요.

2020-01-07 13:38 UTC, ghost approved these changes

2020-01-12 02:18 UTC, workromancer approved these changes
이지 고생하셨어요 ! Approve 할께요 ! 머지 진행해주세요 ㅎㅎ

2020-01-12 06:11 UTC, merged